import { app, BrowserWindow, session, protocol } from 'electron';
import { startBackend, waitForBackend } from './backendManager';
import { initProdEnv } from './prodEnvInit';
import * as path from 'path';
import * as fs from 'fs';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

if (!process.env.NODE_ENV) {
  process.env.NODE_ENV = app.isPackaged ? 'production' : 'development';
  console.log('NODE_ENV fallback:', process.env.NODE_ENV);
}

// Check Monaco resources
const checkMonacoResources = (): void => {
  if (process.env.NODE_ENV === 'production') {
    const appPath = app.getAppPath();
    const vsPath = path.join(appPath, '.webpack', 'renderer', 'vs');
    const exists = fs.existsSync(vsPath);
    console.log(`Monaco resources path: ${vsPath} - ${exists ? 'exist' : 'not exist'}`);
    
    // List the contents of the directory to help with debugging
    if (exists) {
      try {
        const files = fs.readdirSync(vsPath);
        console.log('Monaco resources contents of the directory:', files);
      } catch (err) {
        console.error('Failed to read Monaco resources contents of the directory:', err);
      }
    }
  }
};

const createWindow = (): void => {
  // Check Monaco resources
  checkMonacoResources();

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      webSecurity: true, // Keep web security enabled, but we will configure CSP
      allowRunningInsecureContent: false,
    },
  });

  const rendererCsp =
    process.env.NODE_ENV === 'development'
      ? "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' http://localhost:* ws://localhost:*; img-src 'self' data:; worker-src 'self' blob:;"
      : "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' http://localhost:6785; img-src 'self' data:; worker-src 'self' blob:;";

  // Set Content-Security-Policy for the main document while allowing dev-server websockets.
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    if (details.resourceType !== 'mainFrame' && details.resourceType !== 'subFrame') {
      callback({ responseHeaders: details.responseHeaders });
      return;
    }

    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          rendererCsp
        ]
      }
    });
  });

  // Register custom protocol handlers to help locate Monaco resources
  if (process.env.NODE_ENV === 'production') {
    protocol.registerFileProtocol('monaco', (request, callback) => {
      const url = request.url.substring(9); 
      const appPath = app.getAppPath();
      const filePath = path.join(appPath, '.webpack', 'renderer', url);
      callback(filePath);
    });
  }

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Only open DevTools when explicitly requested so development starts cleanly.
  if (process.env.NODE_ENV === 'development' && process.env.OPEN_DEVTOOLS === 'true') {
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  }

  mainWindow.webContents.on('did-fail-load', (_, errorCode, errorDescription, validatedURL) => {
    console.error(
      `Renderer failed to load (${errorCode}) ${errorDescription} at ${validatedURL}`,
    );
  });

  mainWindow.webContents.on('render-process-gone', (_, details) => {
    console.error(
      `Renderer process exited: reason=${details.reason} exitCode=${details.exitCode}`,
    );
  });

  mainWindow.webContents.on('did-finish-load', () => {
    console.log('Renderer finished loading.');
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  if (process.env.NODE_ENV === 'production') {
    await initProdEnv();
  }
  await startBackend();
  if (process.env.NODE_ENV === 'development') {
    await waitForBackend();
  }
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
