import { app, BrowserWindow, session, protocol } from 'electron';
import { startBackend, waitForBackend } from './backendManager';
import { initProdEnv } from './prodEnvInit';
import * as path from 'path';
import * as fs from 'fs';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

if (process.env.NODE_ENV === 'production') {
  initProdEnv();
}

// 检查Monaco资源
const checkMonacoResources = (): void => {
  if (process.env.NODE_ENV === 'production') {
    const appPath = app.getAppPath();
    const vsPath = path.join(appPath, '.webpack', 'renderer', 'vs');
    const exists = fs.existsSync(vsPath);
    console.log(`Monaco资源路径: ${vsPath} - ${exists ? '存在' : '不存在'}`);
    
    // 列出目录内容以帮助调试
    if (exists) {
      try {
        const files = fs.readdirSync(vsPath);
        console.log('Monaco资源目录内容:', files);
      } catch (err) {
        console.error('读取Monaco资源目录失败:', err);
      }
    }
  }
};

const createWindow = (): void => {
  // 检查Monaco资源
  checkMonacoResources();

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      webSecurity: true, // 保持安全性启用，但我们会配置CSP
      allowRunningInsecureContent: false,
    },
  });

  // 设置CSP以允许Monaco编辑器加载
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; connect-src 'self' http://localhost:*; img-src 'self' data:; worker-src 'self' blob:;"
        ]
      }
    });
  });

  // 注册自定义协议处理程序，帮助定位Monaco资源
  if (process.env.NODE_ENV === 'production') {
    protocol.registerFileProtocol('monaco', (request, callback) => {
      const url = request.url.substring(9); // 移除 'monaco://'
      const appPath = app.getAppPath();
      const filePath = path.join(appPath, '.webpack', 'renderer', url);
      callback(filePath);
    });
  }

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools in development mode
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
  
  // 监听页面加载完成事件，打印调试信息
  mainWindow.webContents.on('did-finish-load', () => {
    console.log('页面加载完成，Monaco编辑器应该开始初始化');
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  await startBackend();
  if (process.env.NODE_ENV === 'development') {
    await waitForBackend();
  }
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
